global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:9187"]
    metrics_path: /metrics

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]
    metrics_path: /metrics

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:7071"]
    metrics_path: /metrics

  - job_name: "spring-boot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8080"]
